// ── src/lib/report-format-defaults.ts ────────────────────────────────────────
// Converts the existing REPORT_SECTIONS config into the new ReportFormatSection
// shape. This is the canonical default format — seeded for every new consultant.

import type { ReportFormatSection } from "@/types/report-format";

export const DEFAULT_FORMAT_SECTIONS: ReportFormatSection[] = [
  {
    key: "executive_summary",
    number: 1,
    title: "1. Executive Summary",
    description:
      "Project overview, key financial highlights, strategic rationale, and feasibility verdict.",
    section_type: "content",
    word_count_target: 500,
    has_placeholders: true,
    generation_phase: 6,
    max_tokens: 4000,
    prompt_hint:
      "Synthesise the entire report into a compelling executive summary. Include a table of contents, key financial highlights table, and a strong feasibility verdict. Generated LAST so it can reference all other sections.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: true,
    builtin_ai_task: "report_executive_summary",
  },
  {
    key: "introduction",
    number: 2,
    title: "2. Introduction",
    description:
      "Country agricultural context, import dependency, project positioning, and objectives.",
    section_type: "market",
    word_count_target: 450,
    has_placeholders: false,
    generation_phase: 1,
    max_tokens: 3000,
    prompt_hint:
      "Introduce the country's agricultural landscape, import dependency figures, the opportunity for greenhouse farming, and the project's strategic positioning. Include 3-4 clear project objectives.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_introduction",
  },
  {
    key: "project_overview",
    number: 3,
    title: "3. Project Overview & About Us",
    description:
      "Investor profile, land and site details, and consultant firm profile.",
    section_type: "content",
    word_count_target: 300,
    has_placeholders: true,
    generation_phase: 1,
    max_tokens: 1500,
    prompt_hint:
      "Describe who the investor is, the land parcels, what makes the site strategic, and the consultant firm's role. Include placeholders for investor profile and consultant profile.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_project_overview",
  },
  {
    key: "market_analysis",
    number: 4,
    title: "4. Market Analysis",
    description:
      "Country agricultural landscape, target crop demand & pricing, export opportunities.",
    section_type: "market",
    word_count_target: 550,
    has_placeholders: false,
    generation_phase: 2,
    max_tokens: 4000,
    prompt_hint:
      "Analyse the agricultural sector, target crop demand and pricing tables, seasonal price premiums, export corridors, and agro-tourism market if applicable. Use live market research data.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_market_analysis",
  },
  {
    key: "target_market",
    number: 5,
    title: "5. Target Market",
    description:
      "Customer segments: domestic retailers, supermarkets, restaurants, exporters.",
    section_type: "market",
    word_count_target: 350,
    has_placeholders: false,
    generation_phase: 2,
    max_tokens: 2000,
    prompt_hint:
      "Define each buyer segment, their specific needs, and how the farm serves them. Include domestic consumers, supermarkets (name local chains), restaurants/hotels, traders, and export markets if selected.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_target_market",
  },
  {
    key: "competitive_analysis",
    number: 6,
    title: "6. Competitive Analysis",
    description:
      "Unique advantages: year-round growing, location, agro-tourism differentiation.",
    section_type: "market",
    word_count_target: 400,
    has_placeholders: false,
    generation_phase: 2,
    max_tokens: 2500,
    prompt_hint:
      "Articulate specific competitive advantages: year-round capability, seasonal pricing premium, location advantage, agro-tourism differentiation. Be specific — avoid generic statements.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_competitive_analysis",
  },
  {
    key: "business_model",
    number: 7,
    title: "7. Business Model",
    description:
      "Farm operations, crop cultivation plan, facility, agro-tourism activities.",
    section_type: "content",
    word_count_target: 600,
    has_placeholders: true,
    generation_phase: 3,
    max_tokens: 3500,
    prompt_hint:
      "Detail the growing structures (dimensions table), crop cultivation plan (table), operation facility components, and agro-tourism activities if planned. Include greenhouse layout placeholder.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_business_model",
  },
  {
    key: "revenue_streams",
    number: 8,
    title: "8. Revenue Streams",
    description:
      "Crop sales, agro-tourism services, accommodation revenue model.",
    section_type: "financial",
    word_count_target: 300,
    has_placeholders: false,
    generation_phase: 3,
    max_tokens: 2000,
    prompt_hint:
      "Explain all revenue streams: crop sales (year-round contract advantage), agro-tourism (if applicable), accommodation (if applicable). Reference actual revenue figures from the financial model.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: true,
    is_excerpt_default: false,
    builtin_ai_task: "report_revenue_streams",
  },
  {
    key: "marketing_sales_plan",
    number: 9,
    title: "9. Marketing & Sales Plan",
    description:
      "Brand positioning, target segments, digital marketing, partnerships.",
    section_type: "content",
    word_count_target: 400,
    has_placeholders: true,
    generation_phase: 3,
    max_tokens: 2500,
    prompt_hint:
      "Cover brand positioning, segmented sales approach, digital channels (WhatsApp Business is critical for GCC B2B), supermarket partnerships, and agro-tourism marketing. Include marketing budget placeholder.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_marketing_sales_plan",
  },
  {
    key: "proposed_machinery",
    number: 10,
    title: "10. Proposed Machinery & Infrastructure",
    description:
      "Greenhouse specs, cooling, irrigation, hydroponics, automation.",
    section_type: "technical",
    word_count_target: 550,
    has_placeholders: true,
    generation_phase: 1,
    max_tokens: 3000,
    prompt_hint:
      "List all infrastructure: hitech greenhouse, pad & fan cooling, circulation fans, automated fertigation, hydroponic growbag system, ground cover, H2O2 generator (advanced), sensor network, agro-tourism infrastructure. Include supplier quotes placeholder.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_proposed_machinery",
  },
  {
    key: "proposed_timelines",
    number: 11,
    title: "11. Proposed Timelines",
    description:
      "Construction and operational timeline narrative with Gantt placeholders.",
    section_type: "operational",
    word_count_target: 400,
    has_placeholders: true,
    generation_phase: 5,
    max_tokens: 2000,
    prompt_hint:
      "Narrative construction timeline (pre-construction → civil → greenhouse → systems → commissioning) and operational timeline (grower hire → licensing → seeding → first harvest). Include Gantt chart placeholders for both.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_proposed_timelines",
  },
  {
    key: "quality_assurance",
    number: 12,
    title: "12. Quality Assurance & Control Plan",
    description:
      "GLOBALG.A.P, ISO 22000, food safety standards and certification roadmap.",
    section_type: "operational",
    word_count_target: 300,
    has_placeholders: false,
    generation_phase: 2,
    max_tokens: 1500,
    prompt_hint:
      "Cover GLOBALG.A.P, ISO 22000, ISO 9001 quality frameworks and what they mean for this farm. Include certification timeline (12-18 months after operation starts) and the premium pricing advantage it unlocks.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_quality_assurance",
  },
  {
    key: "financial_projection",
    number: 13,
    title: "13. Financial Projection",
    description:
      "Investment, production, revenue, operating costs, and profitability summary.",
    section_type: "financial",
    word_count_target: 550,
    has_placeholders: true,
    generation_phase: 3,
    max_tokens: 3000,
    prompt_hint:
      "Use EXACT figures from the financial model. Investment summary table, production projections table, revenue table with seasonal pricing strategy, operating costs including staffing table, profitability summary. Include staffing plan and CAPEX breakdown placeholders.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: true,
    is_excerpt_default: true,
    builtin_ai_task: "report_financial_projection",
  },
  {
    key: "risk_mitigation",
    number: 14,
    title: "14. Risk & Mitigation",
    description:
      "Risk matrix covering utility, production, market, competition, pricing risks.",
    section_type: "risk",
    word_count_target: 450,
    has_placeholders: false,
    generation_phase: 4,
    max_tokens: 3000,
    prompt_hint:
      "Present a risk matrix table covering: utility availability, production (disease/yield), market demand, market penetration, competition, pricing volatility, seasonal risk, regulatory delays, labour. Include sensitivity analysis (25% yield + price drop scenario).",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_risk_mitigation",
  },
  {
    key: "benefits_impact",
    number: 15,
    title: "15. Benefits & Impact",
    description:
      "Socio-economic and environmental benefits aligned with national vision.",
    section_type: "content",
    word_count_target: 400,
    has_placeholders: false,
    generation_phase: 4,
    max_tokens: 2000,
    prompt_hint:
      "Link to the country's Vision/food security policy. Cover: food security, job creation (direct + indirect), technology transfer, economic diversification, tourism/education (if applicable), water efficiency. Be specific to the country's context.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_benefits_impact",
  },
  {
    key: "csr",
    number: 16,
    title: "16. CSR Initiatives",
    description:
      "Community engagement, school partnerships, farmer training programmes.",
    section_type: "operational",
    word_count_target: 300,
    has_placeholders: false,
    generation_phase: 4,
    max_tokens: 1500,
    prompt_hint:
      "Describe CSR initiatives tailored to the country's culture: school farm tours, Ramadan/community food support, farmer training workshops, local employment, women empowerment (if applicable), environmental initiatives.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_csr",
  },
  {
    key: "conclusion",
    number: 17,
    title: "17. Conclusion",
    description:
      "Feasibility verdict, key success factors, and recommended next steps.",
    section_type: "content",
    word_count_target: 300,
    has_placeholders: false,
    generation_phase: 4,
    max_tokens: 2000,
    prompt_hint:
      "Open with a bold feasibility verdict. Reference the EBITDA margin, payback period, and sensitivity analysis results. Align with national Vision. Close with 3 growth levers for Phase 2 and a clear call to action for the investor.",
    ai_generated_prompt: null,
    prompt_confirmed: true,
    is_financial: false,
    is_excerpt_default: false,
    builtin_ai_task: "report_conclusion",
  },
];

export const DEFAULT_FORMAT_EXCERPT_KEYS = ["executive_summary"];
export const DEFAULT_FORMAT_EXCERPT_WORD_LIMIT = 300;
