// ── src/types/report-format.ts ───────────────────────────────────────────────
// Type definitions for the custom report format system.
// Import from "@/types/report-format" in application code.

export type SectionType =
  | "content" // general narrative
  | "financial" // contains financial data / tables
  | "market" // market analysis type
  | "risk" // risk / mitigation
  | "technical" // engineering / infrastructure
  | "operational" // timelines, QA, CSR
  | "custom"; // consultant-defined

export type GenerationPhase = 1 | 2 | 3 | 4 | 5 | 6;

export interface ReportFormatSection {
  /** Unique key within this format. For default sections matches ReportSectionKey.
   *  Custom sections use a slug like "custom_competitive_overview". */
  key: string;

  /** Display number shown in the report (e.g. 1, 2, 3...) */
  number: number;

  /** Section title shown in report and editor */
  title: string;

  /** One-line description for the editor sidebar */
  description: string;

  /** Categorises the section for UI grouping and prompt context */
  section_type: SectionType;

  /** Target word count shown in the editor footer */
  word_count_target: number;

  /** Whether this section has consultant-fill placeholder blocks */
  has_placeholders: boolean;

  /** Generation order (1 = first, 6 = last) */
  generation_phase: GenerationPhase;

  /** Token budget for AI generation */
  max_tokens: number;

  /** Plain-text instruction written by consultant.
   *  Used by AI to generate ai_generated_prompt. */
  prompt_hint: string;

  /** Full prompt template generated by AI from prompt_hint.
   *  null = not yet generated. */
  ai_generated_prompt: string | null;

  /** Whether the consultant has reviewed and confirmed the AI prompt */
  prompt_confirmed: boolean;

  /** True for sections that feed into financial reports */
  is_financial: boolean;

  /** True if this section appears in the excerpt by default */
  is_excerpt_default: boolean;

  /** For built-in sections: the AITask key in prompts.store.ts to use as
   *  fallback when ai_generated_prompt is null. null for pure custom. */
  builtin_ai_task: string | null;
}

export interface ReportFormat {
  id: string;
  consultant_id: string;
  name: string;
  description: string | null;
  is_default: boolean;
  sections: ReportFormatSection[];
  excerpt_section_keys: string[];
  excerpt_word_limit: number;
  created_at: string;
  updated_at: string;
}

// ── Pending section from Word import ─────────────────────────────────────────

export interface DocxImportPendingSection {
  /** Matched existing key, or null if unmatched */
  matched_key: string | null;
  /** Raw heading found in the Word doc */
  title: string;
  /** Extracted content */
  content: string;
  /** True when no existing section matched this heading */
  is_new_section: boolean;
  /** Match confidence 0-1 */
  match_confidence: number;
}

// ── Prompt generation request/response ───────────────────────────────────────

export interface PromptGenerationRequest {
  section_title: string;
  section_type: SectionType;
  prompt_hint: string;
  word_count_target: number;
  report_context: {
    project_type: string;
    crop_types: string[];
    country: string;
    currency: string;
  };
}

export interface PromptGenerationResponse {
  prompt: string;
  suggested_variables: string[];
}
